### ISSUE TITLE
Support of the jQuery-ui datepicker's altField

### ISSUE THREAD

**Issue by chaau** [macek/jquery-serialize-object#62]
It is not a news that dates and JSON are total nightmare. The jQuery-ui datepicker has an [altField](http://api.jqueryui.com/datepicker/#option-altField) element that is together with the altFormat is designed for this:
> This allows one date format to be shown to the user for selection purposes, while a different format is actually sent behind the scenes. 

Unfortunately neither form.serialise() nor form.serializeArray() use this element. As a results dates got passed as a clear text and if you are not happen to live in USA you are in trouble.

I think, it is not difficult to enhance your function to use the altField, as it already re-tests the values from DOM for checkboxes in the encode() function. I recommend it also tests for altField. All it needs to do is check if altField is defined

**Comment by macek** [comment]
This is certainly not the responsibility of this plugin.

I don't know what nightmare you're experiencing with JSON and dates. I suspect it's one of timezones.

```js
// run at 12:21 CDT -5
JSON.stringify(new Date());
// => '"2015-07-08T17:21:39.290Z"'
```

If you actually use a JavaScript `Date` object, it will automatically be converted to UTC (GMT).

As for using the JSON date value? Well watch what happen when I take the JSON time and pass it back to the `Date` constructor

```js
Date("2015-07-08T17:21:39.290Z");
"Wed Jul 08 2015 12:24:46 GMT-0500 (CDT)"
```

I get my original time back. Notice how it's even displaying my correct timezone even though the JSON time string is in UTC. This is because JavaScript is aware of my current [timezone offset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset).

There's nothing inherently wrong with date/time in JSON &mdash; you or your plugin are probably just misunderstanding some fundamental concept.

-----

If you're not using Date objects to generate the correct date strings in your JSON, then yes, you'll likely be in a nightmare situation.

If your plugins are filling in form values for you and they're not using `date.toString()`, then yes, you'll likely be in a nightmare situation.

The solution isn't to offload responsibility to other plugins (such as this one) to catch gimmicky `altField` elements. The solution is for them to fix their garbage plugin or for you to use a better solution altogether.
