### ISSUE TITLE
Issue with mixed keys

### ISSUE THREAD

**Issue by ron666** [macek/jquery-serialize-object#91]
Based on #18 I was able to override fixed using `$.extend(FormSerializer.patterns, {...})` by setting `fixed: /^$/`

The problem is that I have a case like this:

```html
<form id="contact">
  <input name="user[email]" value="jsmith@example.com">
  <input name="user[pets][]" type="checkbox" value="cat" checked>
  <input name="user[pets][]" type="checkbox" value="dog" checked>
  <input name="user[pets][]" type="checkbox" value="bird">
  <input name="user[pets][7]" type="checkbox" value="tiger" checked>
  <input name="user[pets][182]" type="checkbox" value="bull" checked>
  <input name="user[pets][19999]" type="checkbox" value="chicken">
  <input type="submit">
</form>
```

So that thing solves the issue #18 but it's not grabbing the ones that don't have a number between [], any advises on how to achieve this?

**Comment by macek** [comment]
Well your situation is sort of broken, at least as I see it here

What is `7`, `182`, and `19999`? What is their significance?

How do you see the following form working?

```html
<input name="user[pets][]" type="checkbox" value="cat" checked>
<input name="user[pets][]" type="checkbox" value="dog" checked>
<input name="user[pets][1]" type="checkbox" value="bird" checked>
```

The `bird` would overwrite the `dog` value because 

1. `cat` gets pushed onto `user.pets` (at index `0`)
2. `dog` gets pushed onto `user.pets` (at index `1`)
3. `bird` gets manually set to `users.pets[1]`, overwriting the existing value, `dog`

**Comment by ron666** [comment]
These are IDs from the database, but the user adds new elements and we keep the array element open. Well I'll try to check with my team about this. Thanks.
